### ISSUE TITLE
ELK采集的日志信息是否包含k8s的元数据（如pod_name、container_name等）？

### ISSUE THREAD

**Issue by wangzhuzhen** [rootsongjc/docker-images#1]
想了解一下，使用在pod中同时部署app容器和logstsh容器的方式采集日志时，日志中是否能直接获取到 k8s的元数据？

我之前一直使用的是 EFK，就是不能直接采集容器的应用程序的日志，容器标准输入输出的日志是可以的，而且可以直接获取到 k8s的元数据。

**Comment by rootsongjc** [comment]
请参考[应用日志收集](https://github.com/rootsongjc/kubernetes-handbook/blob/master/practice/app-log-collection.md)章节，filebeat收集到ElasticSearch中的日志包含了Pod名称字段，没有容器名称的字段。

**Comment by wangzhuzhen** [comment]
对应的章节昨天已经拜读过，你说的包含 Pod 名称字段，是指 beat.name 的字段吗？ 因为从章节的 Kibana 截图中，没看到 podname 的字段，只看到 beat.hostname 和 beat.name 两个字段。

**Comment by rootsongjc** [comment]
beat.hostname和beat.name就是pod的名称。
