### ISSUE TITLE
镜像问题

### ISSUE THREAD

**Issue by scheng1** [rootsongjc/docker-images#3]
你好，在测试例子中用到的镜像`filebeat:5.4.0`和`analytics-docker-test:Build_8`均不能pull 了，在时速云的hub上看到 镜像已经被删除了，请问现在放到其他镜像仓库了吗？打扰了，多谢。

**Comment by scheng1** [comment]
@rootsongjc

**Comment by rootsongjc** [comment]
filebeat 的镜像是
- index.tenxcloud.com/jimmy/filebeat:5.4.0
anaytics-docker-test:Build_8 是我本地构建的镜像，并没有上传到时速云。

**Comment by rootsongjc** [comment]
可能是这个镜像损坏了，我又重新上传了一个镜像上去，名字和版本不变，你再pull一下试一试。另外直接加我微信在我的微信群里问更方便。 https://jimmysong.io/about

**Comment by scheng1** [comment]
好的 多谢您了。
